### ISSUE TITLE
Script runs into an attribute error

### ISSUE THREAD

**Issue by Williwood** [Psykar/MM-LastFmImportPython#2]
Maybe you find some spare time and stick into this attribute-error. Me and a lot of users would be very happy if you find a solution. Thanks anyway for your hard work. Your script helped me a lot and I am sure a lot more users love this as well!
[Log.txt](https://github.com/Psykar/MM-LastFmImportPython/files/3383575/Log.txt)
![11-07-_2019_21-16-18](https://user-images.githubusercontent.com/2777977/61079142-8c3a8700-a422-11e9-9f8e-0d84ff635d63.png)

**Comment by Psykar** [comment]
@Williwood unfortunately I haven't looked at this (or used MediaMonkey) in quite some years now.
I wouldn't be surprised if both last.fm and MediaMonkey's APIs have changed significantly, and it would likely be non trivial to get working again unfortunately.

**Comment by Williwood** [comment]
Thank you, anyway! I wish you all the best!
